<?xml version="1.0" encoding="utf-8"?><Database Name="SMART" Class="companiasDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=VOSTRO;Initial Catalog=SMART;Integrated Security=True" SettingsObjectName="Smart.DataAccess.Properties.Settings" SettingsPropertyName="SMARTConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.stp_smart_Insert_Compania" Method="stp_smart_Insert_Compania">
    <Parameter Name="intResultado" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="RazonSocial" Parameter="razonSocial" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="RFC" Parameter="rFC" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="NombreBD" Parameter="nombreBD" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="CorreoContacto" Parameter="correoContacto" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="NombreContacto" Parameter="nombreContacto" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="stp_smart_Insert_CompaniaResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_smart_Insert_Perfil" Method="stp_smart_Insert_Perfil">
    <Parameter Name="intResultado" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="Funcion" Parameter="funcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="stp_smart_Insert_PerfilResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_smart_Insert_CompaniasBitacoraAcciones" Method="stp_smart_Insert_CompaniasBitacoraAcciones">
    <Parameter Name="intResultado" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="CompaniaId" Parameter="companiaId" Type="System.Int32" DbType="Int" />
    <Parameter Name="AgregarCompania" Parameter="agregarCompania" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="AgregarMembership" Parameter="agregarMembership" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="AgregarPerfil" Parameter="agregarPerfil" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="EnvioCorreo" Parameter="envioCorreo" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="stp_smart_Insert_CompaniasBitacoraAccionesResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>