#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart.DataAccess.Context
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SMART")]
	public partial class companiasDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public companiasDataContext() : 
				base(global::Smart.DataAccess.Properties.Settings.Default.SMARTConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public companiasDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public companiasDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public companiasDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public companiasDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_smart_Insert_Compania")]
		public ISingleResult<stp_smart_Insert_CompaniaResult> stp_smart_Insert_Compania([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> intResultado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RazonSocial", DbType="VarChar(100)")] string razonSocial, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(150)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RFC", DbType="VarChar(15)")] string rFC, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreBD", DbType="VarChar(15)")] string nombreBD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CorreoContacto", DbType="VarChar(30)")] string correoContacto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreContacto", DbType="VarChar(50)")] string nombreContacto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intResultado, razonSocial, descripcion, rFC, nombreBD, correoContacto, nombreContacto);
			intResultado = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((ISingleResult<stp_smart_Insert_CompaniaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_smart_Insert_Perfil")]
		public ISingleResult<stp_smart_Insert_PerfilResult> stp_smart_Insert_Perfil([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> intResultado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Funcion", DbType="VarChar(100)")] string funcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(150)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intResultado, funcion, descripcion);
			intResultado = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((ISingleResult<stp_smart_Insert_PerfilResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_smart_Insert_CompaniasBitacoraAcciones")]
		public ISingleResult<stp_smart_Insert_CompaniasBitacoraAccionesResult> stp_smart_Insert_CompaniasBitacoraAcciones([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> intResultado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompaniaId", DbType="Int")] System.Nullable<int> companiaId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AgregarCompania", DbType="Bit")] System.Nullable<bool> agregarCompania, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AgregarMembership", DbType="Bit")] System.Nullable<bool> agregarMembership, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AgregarPerfil", DbType="Bit")] System.Nullable<bool> agregarPerfil, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EnvioCorreo", DbType="Bit")] System.Nullable<bool> envioCorreo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intResultado, companiaId, agregarCompania, agregarMembership, agregarPerfil, envioCorreo);
			intResultado = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((ISingleResult<stp_smart_Insert_CompaniasBitacoraAccionesResult>)(result.ReturnValue));
		}
	}
	
	public partial class stp_smart_Insert_CompaniaResult
	{
		
		private System.Nullable<int> _Column1;
		
		public stp_smart_Insert_CompaniaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
		public System.Nullable<int> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class stp_smart_Insert_PerfilResult
	{
		
		private System.Nullable<int> _Column1;
		
		public stp_smart_Insert_PerfilResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
		public System.Nullable<int> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class stp_smart_Insert_CompaniasBitacoraAccionesResult
	{
		
		private System.Nullable<int> _Column1;
		
		public stp_smart_Insert_CompaniasBitacoraAccionesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
		public System.Nullable<int> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
