<?xml version="1.0" encoding="utf-8"?><Database Name="master" Class="ContextTestDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=VOSTRO;Initial Catalog=master;Integrated Security=True" SettingsObjectName="Smart.DataAccess.Properties.Settings" SettingsPropertyName="CS_Test" Provider="System.Data.SqlClient" />
  <Function Name="dbo.stp_ListarTest" Method="stp_ListarTest">
    <ElementType Name="stp_ListarTestResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>