//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart.WebSite.srAdmonSitio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Companias_BE", Namespace="http://schemas.datacontract.org/2004/07/Smart.BussinesEntities")]
    [System.SerializableAttribute()]
    public partial class Companias_BE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CompaniaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsActivaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaSisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreBDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CompaniaId {
            get {
                return this.CompaniaIdField;
            }
            set {
                if ((this.CompaniaIdField.Equals(value) != true)) {
                    this.CompaniaIdField = value;
                    this.RaisePropertyChanged("CompaniaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoContacto {
            get {
                return this.CorreoContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoContactoField, value) != true)) {
                    this.CorreoContactoField = value;
                    this.RaisePropertyChanged("CorreoContacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsActiva {
            get {
                return this.EsActivaField;
            }
            set {
                if ((this.EsActivaField.Equals(value) != true)) {
                    this.EsActivaField = value;
                    this.RaisePropertyChanged("EsActiva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaSis {
            get {
                return this.FechaSisField;
            }
            set {
                if ((this.FechaSisField.Equals(value) != true)) {
                    this.FechaSisField = value;
                    this.RaisePropertyChanged("FechaSis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreBD {
            get {
                return this.NombreBDField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreBDField, value) != true)) {
                    this.NombreBDField = value;
                    this.RaisePropertyChanged("NombreBD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreContacto {
            get {
                return this.NombreContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreContactoField, value) != true)) {
                    this.NombreContactoField = value;
                    this.RaisePropertyChanged("NombreContacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Perfiles_BE", Namespace="http://schemas.datacontract.org/2004/07/Smart.BussinesEntities")]
    [System.SerializableAttribute()]
    public partial class Perfiles_BE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaSisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FuncionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PerfilIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsActivo {
            get {
                return this.EsActivoField;
            }
            set {
                if ((this.EsActivoField.Equals(value) != true)) {
                    this.EsActivoField = value;
                    this.RaisePropertyChanged("EsActivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaSis {
            get {
                return this.FechaSisField;
            }
            set {
                if ((this.FechaSisField.Equals(value) != true)) {
                    this.FechaSisField = value;
                    this.RaisePropertyChanged("FechaSis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Funcion {
            get {
                return this.FuncionField;
            }
            set {
                if ((object.ReferenceEquals(this.FuncionField, value) != true)) {
                    this.FuncionField = value;
                    this.RaisePropertyChanged("Funcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PerfilID {
            get {
                return this.PerfilIDField;
            }
            set {
                if ((this.PerfilIDField.Equals(value) != true)) {
                    this.PerfilIDField = value;
                    this.RaisePropertyChanged("PerfilID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompaniasBitacoraAcciones_BE", Namespace="http://schemas.datacontract.org/2004/07/Smart.BussinesEntities")]
    [System.SerializableAttribute()]
    public partial class CompaniasBitacoraAcciones_BE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AgregarCompaniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AgregarMembershipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AgregarPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompaniaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnvioCorreoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AgregarCompania {
            get {
                return this.AgregarCompaniaField;
            }
            set {
                if ((this.AgregarCompaniaField.Equals(value) != true)) {
                    this.AgregarCompaniaField = value;
                    this.RaisePropertyChanged("AgregarCompania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AgregarMembership {
            get {
                return this.AgregarMembershipField;
            }
            set {
                if ((this.AgregarMembershipField.Equals(value) != true)) {
                    this.AgregarMembershipField = value;
                    this.RaisePropertyChanged("AgregarMembership");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AgregarPerfil {
            get {
                return this.AgregarPerfilField;
            }
            set {
                if ((this.AgregarPerfilField.Equals(value) != true)) {
                    this.AgregarPerfilField = value;
                    this.RaisePropertyChanged("AgregarPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompaniaId {
            get {
                return this.CompaniaIdField;
            }
            set {
                if ((this.CompaniaIdField.Equals(value) != true)) {
                    this.CompaniaIdField = value;
                    this.RaisePropertyChanged("CompaniaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EnvioCorreo {
            get {
                return this.EnvioCorreoField;
            }
            set {
                if ((this.EnvioCorreoField.Equals(value) != true)) {
                    this.EnvioCorreoField = value;
                    this.RaisePropertyChanged("EnvioCorreo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srAdmonSitio.IAdmonSitioContract")]
    public interface IAdmonSitioContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmonSitioContract/insert_Companias", ReplyAction="http://tempuri.org/IAdmonSitioContract/insert_CompaniasResponse")]
        int insert_Companias(Smart.WebSite.srAdmonSitio.Companias_BE compania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmonSitioContract/insert_Companias", ReplyAction="http://tempuri.org/IAdmonSitioContract/insert_CompaniasResponse")]
        System.Threading.Tasks.Task<int> insert_CompaniasAsync(Smart.WebSite.srAdmonSitio.Companias_BE compania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmonSitioContract/insert_Perfiles", ReplyAction="http://tempuri.org/IAdmonSitioContract/insert_PerfilesResponse")]
        int insert_Perfiles(Smart.WebSite.srAdmonSitio.Perfiles_BE perfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmonSitioContract/insert_Perfiles", ReplyAction="http://tempuri.org/IAdmonSitioContract/insert_PerfilesResponse")]
        System.Threading.Tasks.Task<int> insert_PerfilesAsync(Smart.WebSite.srAdmonSitio.Perfiles_BE perfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmonSitioContract/insert_CompaniasBitacoraAcciones", ReplyAction="http://tempuri.org/IAdmonSitioContract/insert_CompaniasBitacoraAccionesResponse")]
        int insert_CompaniasBitacoraAcciones(Smart.WebSite.srAdmonSitio.CompaniasBitacoraAcciones_BE acciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmonSitioContract/insert_CompaniasBitacoraAcciones", ReplyAction="http://tempuri.org/IAdmonSitioContract/insert_CompaniasBitacoraAccionesResponse")]
        System.Threading.Tasks.Task<int> insert_CompaniasBitacoraAccionesAsync(Smart.WebSite.srAdmonSitio.CompaniasBitacoraAcciones_BE acciones);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdmonSitioContractChannel : Smart.WebSite.srAdmonSitio.IAdmonSitioContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdmonSitioContractClient : System.ServiceModel.ClientBase<Smart.WebSite.srAdmonSitio.IAdmonSitioContract>, Smart.WebSite.srAdmonSitio.IAdmonSitioContract {
        
        public AdmonSitioContractClient() {
        }
        
        public AdmonSitioContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdmonSitioContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdmonSitioContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdmonSitioContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int insert_Companias(Smart.WebSite.srAdmonSitio.Companias_BE compania) {
            return base.Channel.insert_Companias(compania);
        }
        
        public System.Threading.Tasks.Task<int> insert_CompaniasAsync(Smart.WebSite.srAdmonSitio.Companias_BE compania) {
            return base.Channel.insert_CompaniasAsync(compania);
        }
        
        public int insert_Perfiles(Smart.WebSite.srAdmonSitio.Perfiles_BE perfil) {
            return base.Channel.insert_Perfiles(perfil);
        }
        
        public System.Threading.Tasks.Task<int> insert_PerfilesAsync(Smart.WebSite.srAdmonSitio.Perfiles_BE perfil) {
            return base.Channel.insert_PerfilesAsync(perfil);
        }
        
        public int insert_CompaniasBitacoraAcciones(Smart.WebSite.srAdmonSitio.CompaniasBitacoraAcciones_BE acciones) {
            return base.Channel.insert_CompaniasBitacoraAcciones(acciones);
        }
        
        public System.Threading.Tasks.Task<int> insert_CompaniasBitacoraAccionesAsync(Smart.WebSite.srAdmonSitio.CompaniasBitacoraAcciones_BE acciones) {
            return base.Channel.insert_CompaniasBitacoraAccionesAsync(acciones);
        }
    }
}
